*&---------------------------------------------------------------------*
*& Include          ZHR_VF03_TOP
*&---------------------------------------------------------------------*

* Tabelas transparentes
TABLES: vbak          ,
        vbap          ,
        prcd_elements ,
        vbrk          ,
        vbrp          ,
        tvzbt         ,
        likp          ,
        lips          ,
        tvakt         ,
        vbkd          ,
        icon          ,
        zht_log_emails.


TYPES: BEGIN OF ty_vbrp,
         vbeln TYPE vbrp-vbeln,
         posnr TYPE vbrp-posnr,
         arktx TYPE vbrp-arktx,
         werks TYPE vbrp-werks,
         fkimg TYPE vbrp-fkimg,
         vgbel TYPE vbrp-vgbel,
         matnr TYPE vbrp-matnr,
       END OF ty_vbrp,

       BEGIN OF ty_vbrk,
         vbeln TYPE vbrk-vbeln,
         vkorg TYPE vbrk-vkorg,
         zterm TYPE vbrk-zterm,
         fkdat TYPE vbrk-fkdat,
         waerk TYPE vbrk-waerk,
       END OF ty_vbrk,

       BEGIN OF ty_tvzbt,
         zterm TYPE tvzbt-zterm,
         vtext TYPE tvzbt-vtext,
         spras TYPE tvzbt-spras,
       END OF ty_tvzbt,

       BEGIN OF ty_fatura,
          VBELN TYPE likp-vbeln,
          vbtyp TYPE likp-vbtyp,
       END OF ty_fatura,

       BEGIN OF ty_imposto,
         knumv TYPE prcd_elements-knumv,
         kposn TYPE prcd_elements-kposn,
         kwert TYPE prcd_elements-kwert,
         kbetr TYPE prcd_elements-kbetr,
         kschl TYPE prcd_elements-kschl,
       END OF ty_imposto,

       BEGIN OF ty_data,
         vbeln  TYPE vbrp-vbeln,
         posnr  TYPE vbrp-posnr,
         arktx  TYPE vbrp-arktx,
         werks  TYPE vbrp-werks,
         fkimg  TYPE vbrp-fkimg,
         vgbel  TYPE vbrp-vgbel,
         matnr  TYPE vbrp-matnr,
         vkorg  TYPE vbrk-vkorg,
         zterm  TYPE vbrk-zterm,
         fkdat  TYPE vbrk-fkdat,
         waerk  TYPE vbrk-waerk,
         knumv  TYPE vbrk-knumv,
         vtweg  TYPE vbrk-vtweg,
         spart  TYPE vbrk-spart,
         pltyp  TYPE vbrk-pltyp,
         vgpos  TYPE vbrp-vgpos,
       END OF ty_data,

       BEGIN OF ty_saida,
         icon     TYPE icon-id,
         vbeln    TYPE vbrp-vbeln,
         posnr    TYPE vbrp-posnr,
         arktx    TYPE vbrp-arktx,
         werks    TYPE vbrp-werks,
         fkimg    TYPE vbrp-fkimg,
         vgbel    TYPE vbrp-vgbel,
         matnr    TYPE vbrp-matnr,
         vkorg    TYPE vbrk-vkorg,
         zterm    TYPE string,
         fkdat    TYPE vbrk-fkdat,
         waerk    TYPE vbrk-waerk,
         knumv    TYPE vbrk-knumv,
         spras    TYPE tvzbt-spras,
         zterm1   TYPE tvzbt-zterm,
         vtext    TYPE tvzbt-vtext,
         kwert    TYPE prcd_elements-kwert,
         kwert1   TYPE prcd_elements-kwert,
         kodat    TYPE likp-kodat,
         tragr    TYPE string,
         vtext1   TYPE ttgrt-vtext,
         aubel    TYPE string,
         kunnr    TYPE vbak-kunnr,
         auart    TYPE string,
         vbeln1   TYPE vbak-vbeln,
         zterm2   TYPE string,
         inco1    TYPE vbkd-inco1,
         inco2    TYPE vbkd-inco2,
         matkl    TYPE string,
         lines2   TYPE string,
         ordvenda TYPE string,
         remessa  TYPE string,
         fatura   TYPE string,
         log      TYPE icon-id,
       END OF ty_saida,

       BEGIN OF ty_likp ,
         vbeln TYPE likp-vbeln,
         kodat TYPE likp-kodat,
         tragr TYPE likp-tragr,
       END OF ty_likp,

       BEGIN OF ty_ttgrt,
         vtext TYPE ttgrt-vtext,
         tragr TYPE ttgrt-tragr,
       END OF ty_ttgrt,

       BEGIN OF ty_vbuk,
         vbeln TYPE vbuk-vbeln,
         wbstk TYPE vbuk-wbstk,
       END OF ty_vbuk,

       BEGIN OF ty_vbak,
         vbeln TYPE vbak-vbeln,
         kunnr TYPE vbak-kunnr,
         auart TYPE vbak-auart,
       END OF ty_vbak,

       BEGIN OF ty_tvakt,
         bezei TYPE tvakt-bezei,
         auart TYPE tvakt-auart,
       END OF ty_tvakt,

       BEGIN OF ty_vbkd,
         vbeln2 TYPE vbkd-vbeln,
         posnr  TYPE vbkd-posnr,
         zterm2 TYPE vbkd-zterm,
         inco1  TYPE vbkd-inco1,
         inco2  TYPE vbkd-inco2,
       END OF ty_vbkd,

       BEGIN OF ty_vbap,
         vbeln TYPE vbap-vbeln,
         posnr TYPE vbap-posnr,
         vgpos TYPE vbap-vgpos,
         matkl TYPE vbap-matkl,
       END OF ty_vbap,

       BEGIN OF ty_item,
         vbeln TYPE vbrp-vbeln,
         posnr TYPE vbrp-posnr,
         werks TYPE vbrp-werks,
         fkimg TYPE vbrp-fkimg,
         matnr TYPE vbrp-matnr,
         matkl TYPE vbrp-matkl,
       END OF ty_item,

       BEGIN OF ty_t023t,
         wgbez TYPE t023t-wgbez,
         matkl TYPE t023t-matkl,
       END OF ty_t023t,

       BEGIN OF ty_saida2,
         status     TYPE zht_log_emails-status,
         userid     TYPE zht_log_emails-userid,
         data       TYPE zht_log_emails-datum,
         hora       TYPE zht_log_emails-hora,
         type       TYPE zht_log_emails-type,
         vbelng     TYPE zht_log_emails-vbelngerado,
         message    TYPE zht_log_emails-message,
         vbeln      TYPE zht_log_emails-vbeln,
       END OF ty_saida2,

       BEGIN OF ty_lips,
         vbeln TYPE lips-vbeln,
         posnr TYPE lips-posnr,
         vgbel TYPE lips-vgbel,
         vgpos TYPE lips-vgpos,
         matkl TYPE lips-matkl,
       END OF ty_lips,

       BEGIN OF ty_icon,
         id   TYPE icon-id,
         name TYPE icon-name,
       END OF ty_icon.
* Tabelas internas
DATA: gt_vbak          TYPE TABLE OF ty_vbak,
      gt_vbrk          TYPE TABLE OF ty_vbrk,
      gt_vbrp          TYPE TABLE OF ty_vbrp,
      gt_vbap          TYPE TABLE OF ty_vbap,
      gt_prcd_elements TYPE TABLE OF prcd_elements,
      gt_t023t         TYPE TABLE OF ty_t023t,
      gt_icon          TYPE TABLE OF ty_icon,
      gt_tvzbt         TYPE TABLE OF ty_tvzbt,
      gt_saida         TYPE TABLE OF ty_saida,
      gt_saida2        TYPE TABLE OF ty_saida2,
      gt_data          TYPE TABLE OF ty_data,
      gt_data2         TYPE TABLE OF ty_saida2,
      gt_imposto       TYPE TABLE OF ty_imposto,
      gt_zterm         TYPE TABLE OF ty_tvzbt,
      gt_vbkd          TYPE TABLE OF ty_vbkd,
      gt_tvakt         TYPE TABLE OF ty_tvakt,
      gt_likp          TYPE TABLE OF ty_likp,
      gt_lips          TYPE TABLE OF ty_lips,
      gt_fieldcat      TYPE lvc_t_fcat,
      gt_fieldcat2     TYPE lvc_t_fcat,
      gt_ttgrt         TYPE TABLE OF ty_ttgrt,
      gt_log_emails    TYPE TABLE OF zht_log_emails.

* Work Area
DATA: gs_vbak          TYPE ty_vbak, "
      gs_vbap          TYPE ty_vbap, "
      gs_data          TYPE ty_data, "
      gs_lips          TYPE ty_lips,
      gs_data2         TYPE ty_saida2,
      gs_imposto       TYPE ty_imposto, "
      gs_saida         TYPE ty_saida, "
      gs_saida2        TYPE ty_saida2,
      gs_fieldcat      TYPE lvc_s_fcat,
      gs_fieldcat2     TYPE lvc_s_fcat,
      gv_linha         TYPE string,
      gs_icon          TYPE ty_icon,
      gv_ordv          TYPE string, "
      gv_remessa       TYPE string, "
      gs_log_emails    TYPE zht_log_emails,
      gv_fatura        TYPE string. "
